import { Component, Injectable, ChangeDetectionStrategy } from '@angular/core';
import { FlatTreeControl } from '@angular/cdk/tree';
import { MatTreeFlatDataSource, MatTreeFlattener } from '@angular/material/tree';
import { ArrayDataSource } from "@angular/cdk/collections";
import {CollectionViewer, DataSource} from '@angular/cdk/collections';
import {BehaviorSubject, Observable, Subscription} from 'rxjs';


export class MyDataSource extends ArrayDataSource<ExampleFlatNode> {
  private _length = 100000;
  private _pageSize = 100;
  private _cachedData = Array.from<ExampleFlatNode>({length: this._length});
  private _fetchedPages = new Set<number>();
  private _dataStream = new BehaviorSubject<(ExampleFlatNode)[]>(this._cachedData);
  private _subscription = new Subscription();

  connect(collectionViewer: CollectionViewer): Observable<ExampleFlatNode[] | readonly ExampleFlatNode[]> {
    this._subscription.add(collectionViewer.viewChange.subscribe(range => {
      const startPage = this._getPageForIndex(range.start);
      const endPage = this._getPageForIndex(range.end - 1);
      for (let i = startPage; i <= endPage; i++) {
        this._fetchPage(i);
      }
    }));
    return this._dataStream;
  }

  disconnect(): void {
    this._subscription.unsubscribe();
  }

  private _getPageForIndex(index: number): number {
    return Math.floor(index / this._pageSize);
  }

  private _fetchPage(page: number) {
    if (this._fetchedPages.has(page)) {
      return;
    }
    this._fetchedPages.add(page);

    // Use `setTimeout` to simulate fetching data from server.
    setTimeout(() => {
      this._cachedData.splice(page * this._pageSize, this._pageSize,
          ...Array.from({length: this._pageSize})
              .map((_, i) => `Item #${page * this._pageSize + i}`));
      this._dataStream.next(this._cachedData);
    }, Math.random() * 1000 + 200);
  }
}

// Interface used for representing a node of data
export interface FakeNode {
  ObjectName: string;
  children: FakeNode[];
}

const MAX_LEVELS = 3;
const MAX_NODES_PER_LEVEL = 5; 

const TREE_DATA: ExampleFlatNode[] = [
  {
    ObjectName: 'Fruit',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Apple',
    expandable: false,
    Level: 1,
  }, {
    ObjectName: 'Banana',
    expandable: false,
    Level: 1,
  }, {
    ObjectName: 'Fruit loops',
    expandable: false,
    Level: 1,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Vegetables',
    expandable: true,
    Level: 0,
  }, {
    ObjectName: 'Green',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Broccoli',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Brussel sprouts',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Orange',
    expandable: true,
    Level: 1,
  }, {
    ObjectName: 'Pumpkins',
    expandable: false,
    Level: 2,
  }, {
    ObjectName: 'Carrots',
    expandable: false,
    Level: 2,
  }
];

interface ExampleFlatNode {
  expandable: boolean;
  ObjectName: string;
  Level: number;
  isExpanded?: boolean;
}

// Generates fake data
@Injectable()
export class RandomDataProvider {
  data: FakeNode[] = [];

  constructor() {
    for(let i = 0; i < MAX_NODES_PER_LEVEL; i++) {
      this.data.push(generateNode(0, i));
    }
  }
}

// Function for generating a fake data node
function generateNode(Level: number, index: number): FakeNode {
  let children: FakeNode[] = [];
  if (Level < MAX_LEVELS) {
    for (let i = 0; i < Math.round(Math.random() * MAX_NODES_PER_LEVEL); i++) {
      children.push(generateNode(Level + 1, i));
    }
  }

  return {
    ObjectName: 'Level ' + Level + ' index ' + index,
    children,
  };
}

// Interface used for representing a node of data within the flat tree component
export interface FakeFlatNode {
  ObjectName: string;
  Level: number;
  hasChildren: boolean;
}

// Component containing virtual scrolling flat tree 
@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ],
  providers: [RandomDataProvider],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent  {

  treeControl1 = new FlatTreeControl<ExampleFlatNode>(
    node => node.Level,
    node => node.expandable
  );

  arrayDataSource = new ArrayDataSource(TREE_DATA);

  hasChild = (_: number, node: ExampleFlatNode) => node.expandable;


  // Provided generated data
  readonly providedData = this.dataProvider.data;
  // Tree control to feed to the cdk tree 
  readonly treeControl: FlatTreeControl<FakeFlatNode> = 
    new FlatTreeControl<FakeFlatNode>(getNodeLevel, getIsNodeExpandable);
  // Data source fed into the cdk tree control 
  readonly dataSource: MatTreeFlatDataSource<FakeNode, FakeFlatNode>;

  constructor(readonly dataProvider: RandomDataProvider) {
    // Tells tree data source builder how to flatten our nested node data into flat nodes
    const treeFlattener = 
      new MatTreeFlattener<FakeNode, FakeFlatNode>(
        nodeTransformer, 
        getNodeLevel, 
        getIsNodeExpandable, 
        getNodeChildren,
      );
    // Populates our flattened data into the tree control
    this.dataSource = new MatTreeFlatDataSource(this.treeControl, treeFlattener);
    this.dataSource.data = this.providedData;
    console.log(this.dataSource.data);
  }

  // Number of dom nodes rendered in the virtually scrolling tree
  get numTreeNodes() {
    return document.querySelectorAll('.node').length;
  }

  // Number of dom nodes rendered in the non-virtually scrolling cdk-tree
  get numCdkTreeNodes() {
    return document.querySelectorAll('cdk-tree-node').length;
  }

  hasChild1(index: number, nodeData: FakeFlatNode) {
    return getIsNodeExpandable(nodeData);
  }

  getParentNode(node: ExampleFlatNode) {
    const nodeIndex = TREE_DATA.indexOf(node);

    for (let i = nodeIndex - 1; i >= 0; i--) {
      if (TREE_DATA[i].Level === node.Level - 1) {
        return TREE_DATA[i];
      }
    }

    return null;
  }

  shouldRender(node: ExampleFlatNode) {
    const parent = this.getParentNode(node);
    return !parent || parent.isExpanded;
  }

  isExpandable(node: ExampleFlatNode): boolean {
    const nodeIndex = TREE_DATA.indexOf(node);
    if (TREE_DATA.length > nodeIndex) {
      const belowItem = TREE_DATA[nodeIndex + 1];
      return belowItem.Level == node.Level + 1;
    }
    return false
  }
}

// Function that maps a nested node to a flat node
function nodeTransformer(node: FakeNode, Level: number) {
  return {
    ObjectName: node.ObjectName,
    Level,
    hasChildren: node.children.length > 0,
  };
}

// Function that gets a flat node's Level
function getNodeLevel({Level}: FakeFlatNode) {
  return Level;
}

// Function that determines whether a flat node is expandable or not
function getIsNodeExpandable({hasChildren}: FakeFlatNode) {
  return hasChildren;
}

// Function that returns a nested node's list of children 
function getNodeChildren({children}: FakeNode) {
  return children;
}